apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: k0smotron
  labels:
    k0smotron-provider: control-plane
spec:
  template:
    spec:
      containers:
      - name: manager
